config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :friends
  resources :likes
  resources :tweets   
  devise_for :users, controllers:{registrations: 'registrations'}
  get 'search' => 'search#index'
  root 'home#index'  
  resources :tweets do
    resources :likes
  end

  

    #devise_scope :user do
    #  get "/home_privados/index" => "home_privados_controller"
    #end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :tweet_hash_tags
  has_many :hash_tags, through: :tweet_hash_tags
  validates :post, presence: true
  


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:new, :create, :show]
  # GET /tweets
  # GET /tweets.json
  
  def index
    
    friends = Friend.where("user_id=?" , current_user&.id)
    #obtengo los amigos del usuario
    aux2=friends.pluck :friend_id
    #saco los twitter de los amigos
    if params[:content].present?
      aux = Tweet.where(user_id: aux2)
      aux2 = aux.where("post ILIKE ?", "%#{params[:content]}%")
      @tweets = aux2.order("created_at DESC").page(params[:page]).per_page(5)
    else
      aux = Tweet.where(user_id: aux2)
      @tweets = aux.order("created_at DESC").page(params[:page]).per_page(5)
    end

  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    
    @tweet = current_user.tweets.new(tweet_params)
    
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
    extract_name_hash_tags.each do |name|
      HashTag.create(name: name)
    end
  end

  def extract_name_hash_tags
    @tweet.post.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end
 
 
 
  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  
  
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:post)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :post %>
    <%= form.text_area :post %>
  </div>


  <div class="field">
    <%= form.label :user_id %>
    <%= current_user.id %>
    
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bienvenido a Twitter</h1>
<p>Estos son los twitter tuyos y de tus amigos</p>
<% if user_signed_in? %>
    <p align="right">Bienvenido <%= current_user.user_name %></p>
<% end %>
<nav class="navbar navbar-light bg-light justify-content-between">
 <a class="navbar-brand">Busque por contenido</a>
 <form class="form-inline">
 <input class="form-control mr-sm-2" type="content" placeholder="Search" aria-label="Search" name="content">
 <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
 </form>
</nav>

<%= button_to 'Nuevo Tweet', new_tweet_path, method: 'get' %>

<%= will_paginate @tweets, previous_label: h("<"), next_label: h(">") %>
<table class="table table-striped">
  <thead>
    <tr >
    
      <th scope="col">#</th>
      <th scope="col">Post</th>
      <th scope="col" align="center">User</th>
      <th scope="col" >Creado</th>
      <th scope="col" align="center">#Likes</th>
      <th scope="col" align="center">#Retweets</th>
      <th scope="col" colspan="3" align="center">Acciones</th>
    
    </tr>
  </thead>

  <tbody>
    <% a = 1 %>
    <% @tweets.each do |tweet| %>
      <tr>
      
        <th scope="row"><%= a + (5*(@tweets.current_page-1)) %> </th>
        
        <td><% tweet.post.to_s.split(' ').each do |word| %>
          <% if word.start_with?('#') %>
            <%= link_to word, tweets_path(word) %>
          <% else %>
            <%=word %>
          <% end %>    
        <% end %>  </td>
         
        
        
        <td align="center"><%= image_tag(tweet.user.user_photo, style: "max-width: 50px; border-radius: 20px;") %></td>
        <td align="center"><%= time_ago_in_words(tweet.user.created_at) %></td>
        <td align="center"><%= tweet.likes.count%></td>
        <td align="center">2</td>
        <td align="center"><%= link_to 'Show', tweet %></td>
        <td align="center"><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td align="center"><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% a = a + 1 %>
    <% end %>
  </tbody>
</table>


<br>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>User:</strong>
  <%= @tweet.user.user_name %>
  <%= image_tag(@tweet.user.user_photo, style: "max-width: 60px; border-radius: 10px;") if @tweet.user.user_photo? %>
</p>
<p>
  <strong>Post:</strong>
  <%= @tweet.post %>
</p>




<p>

  <%= button_to 'Like', tweet_likes_path(@tweet), method: :post %>
  <%= button_to 'ReTweetear', tweet_likes_path(@tweet) %>
</p>

<br><br>
<p>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>
</p>